const questions = [
  {
    id: 1,
    question: "What is 15 + 27?",
    options: ["32", "42", "38", "45"],
    answer: "42",
  },
  {
    id: 2,
    question: "If TRAIN is coded as UQBJO, how is PLANE coded?",
    options: ["QMBOF", "QNBOF", "PMBOE", "QLBOF"],
    answer: "QMBOF",
  },
  {
    id: 3,
    question: "Which number comes next in the series: 2, 6, 12, 20, 30, ?",
    options: ["36", "40", "42", "44"],
    answer: "42",
  },
  {
    id: 4,
    question: "The average of 10, 20, 30 and 40 is:",
    options: ["20", "25", "30", "35"],
    answer: "25",
  },
  {
    id: 5,
    question: "Choose the correct synonym of 'Rapid'.",
    options: ["Slow", "Quick", "Weak", "Calm"],
    answer: "Quick",
  },
  {
    id: 6,
    question: "A man walks 5 km north and then 3 km east. How far is he from the starting point?",
    options: ["8 km", "5.8 km", "6 km", "4 km"],
    answer: "5.8 km",
  },
  {
    id: 7,
    question: "What is the square root of 144?",
    options: ["10", "11", "12", "13"],
    answer: "12",
  },
  {
    id: 8,
    question: "Find the odd one out.",
    options: ["Triangle", "Square", "Rectangle", "Circle"],
    answer: "Circle",
  },
  {
    id: 9,
    question: "If the cost price is ₹800 and selling price is ₹920, the profit percentage is:",
    options: ["12%", "15%", "18%", "20%"],
    answer: "15%",
  },
  {
    id: 10,
    question: "Which word is correctly spelled?",
    options: ["Accomodation", "Accommodation", "Acommodation", "Acomodation"],
    answer: "Accommodation",
  },
  {
    id: 11,
    question: "If 3x + 9 = 24, then x = ?",
    options: ["3", "4", "5", "6"],
    answer: "5",
  },
  {
    id: 12,
    question: "A clock shows 3:15. What is the angle between the hour and minute hands?",
    options: ["0°", "7.5°", "15°", "22.5°"],
    answer: "7.5°",
  },
  {
    id: 13,
    question: "Complete the analogy: Book : Read :: Song : ?",
    options: ["Hear", "Sing", "Dance", "Write"],
    answer: "Hear",
  },
  {
    id: 14,
    question: "What is 25% of 360?",
    options: ["80", "90", "100", "120"],
    answer: "90",
  },
  {
    id: 15,
    question: "Which one is a prime number?",
    options: ["21", "27", "29", "35"],
    answer: "29",
  },
  {
    id: 16,
    question: "Choose the antonym of 'Expand'.",
    options: ["Increase", "Stretch", "Contract", "Grow"],
    answer: "Contract",
  },
  {
    id: 17,
    question: "What comes next: A, C, F, J, O, ?",
    options: ["S", "T", "U", "V"],
    answer: "U",
  },
  {
    id: 18,
    question: "A train 120 m long passes a pole in 6 seconds. Its speed is:",
    options: ["20 m/s", "18 m/s", "24 m/s", "15 m/s"],
    answer: "20 m/s",
  },
  {
    id: 19,
    question: "If all roses are flowers and some flowers fade quickly, which statement is definitely true?",
    options: ["All flowers are roses", "Some roses fade quickly", "All roses are flowers", "No flower fades quickly"],
    answer: "All roses are flowers",
  },
  {
    id: 20,
    question: "Simplify: 48 ÷ 6 × 2",
    options: ["4", "8", "12", "16"],
    answer: "16",
  },
  {
    id: 21,
    question: "Choose the correct passive voice: 'They completed the project.'",
    options: ["The project is completed by them.", "The project was completed by them.", "The project had completed by them.", "The project completed by them."],
    answer: "The project was completed by them.",
  },
  {
    id: 22,
    question: "The ratio 3:5 is equal to:",
    options: ["15:20", "9:15", "12:25", "18:20"],
    answer: "9:15",
  },
  {
    id: 23,
    question: "Find the missing term: 7, 14, 28, 56, ?",
    options: ["64", "96", "112", "120"],
    answer: "112",
  },
  {
    id: 24,
    question: "One dozen equals:",
    options: ["10", "11", "12", "13"],
    answer: "12",
  },
  {
    id: 25,
    question: "If today is Monday, what day will it be after 45 days?",
    options: ["Monday", "Tuesday", "Wednesday", "Sunday"],
    answer: "Tuesday",
  },
  {
    id: 26,
    question: "Which is the largest fraction?",
    options: ["3/5", "5/8", "7/10", "2/3"],
    answer: "7/10",
  },
  {
    id: 27,
    question: "Choose the correctly arranged sentence.",
    options: ["Always she comes late.", "She comes always late.", "She always comes late.", "Late she always comes."],
    answer: "She always comes late.",
  },
  {
    id: 28,
    question: "What is the value of 2^5?",
    options: ["10", "16", "32", "64"],
    answer: "32",
  },
  {
    id: 29,
    question: "Which number is divisible by both 3 and 5?",
    options: ["10", "15", "20", "25"],
    answer: "15",
  },
  {
    id: 30,
    question: "Choose the correct meaning of 'Optimistic'.",
    options: ["Hopeful", "Careless", "Angry", "Proud"],
    answer: "Hopeful",
  },
];

module.exports = questions;
